CREATE TABLE JOB_TITLE (
    ID_JOB_TITLE NUMBER NOT NULL AUTO_INCREMENT,
    NAME_VALUE VARCHAR2(50) NOT NULL
);

CREATE TABLE COMPANY (
    ID_COMPANY NUMBER NOT NULL AUTO_INCREMENT,
    NAME_VALUE VARCHAR2(50) NOT NULL
);

CREATE TABLE TECHNOLOGY (
    ID_TECHNOLOGY NUMBER NOT NULL AUTO_INCREMENT,
    NAME_VALUE VARCHAR2(50) NOT NULL
);

CREATE TABLE WORK_EXPERIENCE_TECHNOLOGY (
    ID_WORK_EXPERIENCE RAW(16) NOT NULL,
    ID_TECHNOLOGY NUMBER NOT NULL
);

CREATE TABLE WORK_EXPERIENCE (
    ID_WORK_EXPERIENCE RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    ID_JOB_TITLE NUMBER NOT NULL,
    VISIBILITY_JOB_TITLE BOOLEAN NOT NULL,
    ID_COMPANY NUMBER NOT NULL,
    VISIBILITY_COMPANY BOOLEAN NOT NULL,
    VISIBILITY_TECHNOLOGIES BOOLEAN NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE,
    VISIBILITY_WORK_PERIOD BOOLEAN NOT NULL
);