INSERT INTO JOB_TITLE(NAME_VALUE) VALUES ('ANALISTA/PROGRAMADOR');
INSERT INTO JOB_TITLE(NAME_VALUE) VALUES ('ARQUITECTO DE SOFTWARE');

INSERT INTO COMPANY(NAME_VALUE) VALUES ('SOPRA STERIA');
INSERT INTO COMPANY(NAME_VALUE) VALUES ('BABEL');
INSERT INTO COMPANY(NAME_VALUE) VALUES ('COGNIZANT');
INSERT INTO COMPANY(NAME_VALUE) VALUES ('HCL');

INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('JAVA');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('SQL');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('JAVASCRIPT');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('PYTHON');

INSERT INTO WORK_EXPERIENCE (
    ID_WORK_EXPERIENCE,
    CREATED_AT,
    USER_ID,
    BINDING,
    ID_JOB_TITLE,
    VISIBILITY_JOB_TITLE,
    ID_COMPANY,
    VISIBILITY_COMPANY,
    VISIBILITY_TECHNOLOGIES,
    START_DATE,
    END_DATE,
    VISIBILITY_WORK_PERIOD
) VALUES (
    '4C714C8E9D5F11EBA8B30242AC130003',
    current_timestamp,
    'TEST_USER_1',
    true,
    1,
    true,
    1,
    true,
    true,
    TO_DATE('01/12/2015', 'DD/MM/YYYY'),
    TO_DATE('01/01/2016', 'DD/MM/YYYY'),
    true
);

INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 1);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 2);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 3);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 4);

