INSERT INTO JOB_TITLE(NAME_VALUE) VALUES ('ANALISTA/PROGRAMADOR');
INSERT INTO JOB_TITLE(NAME_VALUE) VALUES ('ARQUITECTO DE SOFTWARE');

INSERT INTO COMPANY(NAME_VALUE) VALUES ('SOPRA STERIA');
INSERT INTO COMPANY(NAME_VALUE) VALUES ('ARQUIMEA INGENIERÍA');
INSERT INTO COMPANY(NAME_VALUE) VALUES ('BABEL');
INSERT INTO COMPANY(NAME_VALUE) VALUES ('COGNIZANT');
INSERT INTO COMPANY(NAME_VALUE) VALUES ('HCL');

INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('JAVA');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('JAVASCRIPT');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('SPRING');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('ANGULAR');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('SPRING BOOT');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('MICROSOFT AZURE');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('OPENSHIFT');
INSERT INTO TECHNOLOGY(NAME_VALUE) VALUES ('JAVA 11');

INSERT INTO WORK_EXPERIENCE (
    ID_WORK_EXPERIENCE,
    CREATED_AT,
    USER_ID,
    BINDING,
    ID_JOB_TITLE,
    VISIBILITY_JOB_TITLE,
    ID_COMPANY,
    VISIBILITY_COMPANY,
    VISIBILITY_TECHNOLOGIES,
    START_DATE,
    END_DATE,
    VISIBILITY_WORK_PERIOD,
    SALARY,
    CURRENCY,
    VISIBILITY_SALARY
) VALUES (
    '4C714C8E9D5F11EBA8B30242AC130003',
    current_timestamp,
    '5689851',
    true,
    1,
    true,
    1,
    true,
    true,
    TO_DATE('01/06/2014', 'DD/MM/YYYY'),
    TO_DATE('01/06/2017', 'DD/MM/YYYY'),
    true,
    12000,
    'EUR',
    true
);


INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 1);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 2);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 3);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('4C714C8E9D5F11EBA8B30242AC130003', 4);

INSERT INTO WORK_EXPERIENCE (
    ID_WORK_EXPERIENCE,
    CREATED_AT,
    USER_ID,
    BINDING,
    ID_JOB_TITLE,
    VISIBILITY_JOB_TITLE,
    ID_COMPANY,
    VISIBILITY_COMPANY,
    VISIBILITY_TECHNOLOGIES,
    START_DATE,
    END_DATE,
    VISIBILITY_WORK_PERIOD,
    SALARY,
    CURRENCY,
    VISIBILITY_SALARY
) VALUES (
    'B6B3705E9E0411EBA8B30242AC130003',
    current_timestamp,
    '19934271',
    false,
    1,
    false,
    2,
    false,
    false,
    TO_DATE('28/01/2017', 'DD/MM/YYYY'),
    null,
    false,
    34000,
    'EUR',
    false
);

INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('B6B3705E9E0411EBA8B30242AC130003', 5);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('B6B3705E9E0411EBA8B30242AC130003', 6);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('B6B3705E9E0411EBA8B30242AC130003', 7);
INSERT INTO WORK_EXPERIENCE_TECHNOLOGY (ID_WORK_EXPERIENCE, ID_TECHNOLOGY) VALUES
('B6B3705E9E0411EBA8B30242AC130003', 8);

