-- REQUESTED_DATA
CREATE TABLE REQUESTED_DATA (
    ID_REQUESTED_DATA NUMBER NOT NULL AUTO_INCREMENT,
    JOB_TITLE VARCHAR2(50) NOT NULL,
    COMPANY VARCHAR2(50) NOT NULL,
    TECHNOLOGIES VARCHAR2(50) NOT NULL,
    WORK_PERIOD VARCHAR2(50) NOT NULL,
    SALARY VARCHAR2(50) NOT NULL
);

ALTER TABLE REQUESTED_DATA
ADD CONSTRAINT PK_REQUESTED_DATA PRIMARY KEY (ID_REQUESTED_DATA);

-- NEGOTIATION
CREATE TABLE NEGOTIATION (
    ID_NEGOTIATION RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    ID_OFFERED_WORK_EXPERIENCE RAW(16) NOT NULL,
    ID_DEMANDED_WORK_EXPERIENCE RAW(16) NOT NULL,
    CREATOR_ID VARCHAR2(50) NOT NULL,
    RECEIVER_ID VARCHAR2(50) NOT NULL,
    NEXT_ACTOR VARCHAR2(50)
);

ALTER TABLE NEGOTIATION
ADD CONSTRAINT PK_NEGOTIATION PRIMARY KEY (ID_NEGOTIATION);

ALTER TABLE NEGOTIATION
ADD CONSTRAINT FK_N_OFFERED_WE
FOREIGN KEY (ID_OFFERED_WORK_EXPERIENCE) REFERENCES WORK_EXPERIENCE(ID_WORK_EXPERIENCE);

ALTER TABLE NEGOTIATION
ADD CONSTRAINT FK_N_DEMANDED_WE
FOREIGN KEY (ID_DEMANDED_WORK_EXPERIENCE) REFERENCES WORK_EXPERIENCE(ID_WORK_EXPERIENCE);

-- NEGOTIATION_ACTION
CREATE TABLE NEGOTIATION_ACTION (
    ID_NEGOTIATION_ACTION NUMBER NOT NULL AUTO_INCREMENT,
    ID_NEGOTIATION RAW(16) NOT NULL,
    ACTION_DATE TIMESTAMP NOT NULL,
    TYPE VARCHAR2(50) NOT NULL,
    ISSUER_ID VARCHAR2(50) NOT NULL,
    ID_OFFERED_DATA NUMBER NOT NULL,
    ID_DEMANDED_DATA NUMBER NOT NULL
);

ALTER TABLE NEGOTIATION_ACTION
ADD CONSTRAINT PK_NEGOTIATION_ACTION PRIMARY KEY (ID_NEGOTIATION_ACTION, ID_NEGOTIATION);

ALTER TABLE NEGOTIATION_ACTION
ADD CONSTRAINT FK_NA_NEGOTIATION
FOREIGN KEY (ID_NEGOTIATION) REFERENCES NEGOTIATION(ID_NEGOTIATION);

ALTER TABLE NEGOTIATION_ACTION
ADD CONSTRAINT FK_NA_OFFERED_RD
FOREIGN KEY (ID_OFFERED_DATA) REFERENCES REQUESTED_DATA(ID_REQUESTED_DATA);

ALTER TABLE NEGOTIATION_ACTION
ADD CONSTRAINT FK_NA_DEMANDED_RD
FOREIGN KEY (ID_DEMANDED_DATA) REFERENCES REQUESTED_DATA(ID_REQUESTED_DATA);