-- REQUESTED_DATA
CREATE TABLE REQUESTED_DATA (
    ID_REQUESTED_DATA NUMBER NOT NULL AUTO_INCREMENT,
    ID_WORK_EXPERIENCE RAW(16) NOT NULL,
    JOB_TITLE VARCHAR2(50) NOT NULL,
    COMPANY VARCHAR2(50) NOT NULL,
    TECHNOLOGIES VARCHAR2(50) NOT NULL,
    WORK_PERIOD VARCHAR2(50) NOT NULL,
    SALARY VARCHAR2(50) NOT NULL
);

ALTER TABLE REQUESTED_DATA
ADD CONSTRAINT PK_REQUESTED_DATA PRIMARY KEY (ID_REQUESTED_DATA);

ALTER TABLE REQUESTED_DATA
ADD CONSTRAINT FK_RD_WE
FOREIGN KEY (ID_WORK_EXPERIENCE) REFERENCES WORK_EXPERIENCE(ID_WORK_EXPERIENCE);

-- NEGOTIATION
CREATE TABLE NEGOTIATION (
    ID_NEGOTIATION RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    ID_OFFERED_DATA NUMBER NOT NULL,
    ID_DEMANDED_DATA NUMBER NOT NULL,
    STATE VARCHAR2(50) NOT NULL
);

ALTER TABLE NEGOTIATION
ADD CONSTRAINT PK_NEGOTIATION PRIMARY KEY (ID_NEGOTIATION);

ALTER TABLE NEGOTIATION
ADD CONSTRAINT FK_N_OFFERED_RD
FOREIGN KEY (ID_OFFERED_DATA) REFERENCES REQUESTED_DATA(ID_REQUESTED_DATA);

ALTER TABLE NEGOTIATION
ADD CONSTRAINT FK_N_DEMANDED_RD
FOREIGN KEY (ID_DEMANDED_DATA) REFERENCES REQUESTED_DATA(ID_REQUESTED_DATA);